# Generated by Django 5.1.5 on 2025-03-08 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_pub_date_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 19, 26, 19, 192532, tzinfo=datetime.timezone.utc)),
        ),
    ]
