# Generated by Django 5.1.5 on 2025-03-08 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 19, 29, 20, 183432, tzinfo=datetime.timezone.utc)),
        ),
    ]
