# Generated by Django 5.1.5 on 2025-03-10 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_alter_article_pub_date_alter_article_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 19, 8, 10, 682000, tzinfo=datetime.timezone.utc)),
        ),
    ]
