# Generated by Django 5.1.5 on 2025-03-15 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='myfile',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 2, 9, 10, 120891, tzinfo=datetime.timezone.utc)),
        ),
    ]
