# Generated by Django 5.1.5 on 2025-03-15 02:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_article_myfile_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='myfile',
            field=models.FileField(null=True, upload_to='test'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 15, 2, 21, 33, 473147, tzinfo=datetime.timezone.utc)),
        ),
    ]
