# Generated by Django 5.1.5 on 2025-04-15 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_myfile_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 15, 21, 3, 692271, tzinfo=datetime.timezone.utc)),
        ),
    ]
